#!/bin/bash

# 🎨 Demo: Show where icons will be generated

echo "🎨 MATH WAR - ICON GENERATION PREVIEW"
echo "========================================"
echo ""
echo "Sau khi chạy ./setup_icon.sh, icons sẽ được tạo ở:"
echo ""

echo "📱 ANDROID (Adaptive Icons)"
echo "└── android/app/src/main/res/"
echo "    ├── mipmap-mdpi/       (48x48 dp)    [~HDPI phones]"
echo "    │   ├── ic_launcher.png"
echo "    │   ├── ic_launcher_foreground.png"
echo "    │   └── ic_launcher_background.png"
echo "    ├── mipmap-hdpi/       (72x72 dp)    [720p screens]"
echo "    ├── mipmap-xhdpi/      (96x96 dp)    [1080p screens]"
echo "    ├── mipmap-xxhdpi/     (144x144 dp)  [1440p screens]"
echo "    └── mipmap-xxxhdpi/    (192x192 dp)  [4K screens]"
echo ""

echo "🍎 iOS (All Devices)"
echo "└── ios/Runner/Assets.xcassets/AppIcon.appiconset/"
echo "    ├── Icon-App-20x20@2x.png      (40x40 px)    [Notification]"
echo "    ├── Icon-App-20x20@3x.png      (60x60 px)"
echo "    ├── Icon-App-29x29@2x.png      (58x58 px)    [Settings]"
echo "    ├── Icon-App-29x29@3x.png      (87x87 px)"
echo "    ├── Icon-App-40x40@2x.png      (80x80 px)    [Spotlight]"
echo "    ├── Icon-App-40x40@3x.png      (120x120 px)"
echo "    ├── Icon-App-60x60@2x.png      (120x120 px)  [iPhone App]"
echo "    ├── Icon-App-60x60@3x.png      (180x180 px)  [iPhone App]"
echo "    ├── Icon-App-76x76@1x.png      (76x76 px)    [iPad App]"
echo "    ├── Icon-App-76x76@2x.png      (152x152 px)  [iPad App]"
echo "    ├── Icon-App-83.5x83.5@2x.png  (167x167 px)  [iPad Pro]"
echo "    └── Icon-App-1024x1024@1x.png  (1024x1024 px) [App Store]"
echo ""

echo "🌐 WEB (PWA + Favicon)"
echo "├── web/icons/"
echo "│   ├── Icon-192.png           (192x192 px)   [PWA Small]"
echo "│   ├── Icon-512.png           (512x512 px)   [PWA Large]"
echo "│   ├── Icon-maskable-192.png  (192x192 px)   [Adaptive]"
echo "│   └── Icon-maskable-512.png  (512x512 px)   [Adaptive]"
echo "└── web/favicon.png            (16x16 px)     [Browser Tab]"
echo ""

echo "========================================"
echo ""
echo "📊 TỔNG SỐ FILE SẼ ĐƯỢC TẠO:"
echo "   • Android: ~15 files (5 densities × 3 types)"
echo "   • iOS: 15 files"
echo "   • Web: 5 files"
echo "   • TOTAL: ~35 icon files"
echo ""

echo "⚡ READY TO START?"
echo ""
echo "1. Đặt icon vào:  assets/app_icon.png"
echo "2. Chạy script:   ./setup_icon.sh"
echo "3. Test app:      flutter run"
echo ""
